baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/clevergo/website/edit/master/content/"
  description = "Documentation for CleverGo"
  author = "Razon Yang"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  baiduAnalytics = "afba29a2d051b29ccf73018b8c9df89c"
  disableSearch = false
  themeVariant = "blue"
  disqusShortname = "clevergo"
  titleSeparator = "-"

[params.beian]
  no = "粤公网安备44040302000337号"
  link = "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44040302000337"
  icpNo = "粤ICP备20043980号"
  icpLink = "http://beian.miit.gov.cn/"

[params.docsearch]
  api_key = "6e86444395683d3c6fb2d97c278095c8"
  index_name = "clevergo"
  input_selector = "#searchBy"
  debug = false # Set debug to true if you want to inspect the dropdown


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "CleverGo"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
url = "https://github.com/clevergo/website"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-eye'></i> Examples"
url = "https://github.com/clevergo/examples"
weight = 20

[Languages.zh]
title = "CleverGo"
weight = 2
languageName = "简体中文"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
url = "https://github.com/clevergo/website"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-eye'></i> 示例"
url = "https://github.com/clevergo/examples"
weight = 20